version: "3.7"
services:
  meetMe:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: "meetme"
    container_name: "MeetMe"
    ports:
    - "80:80"
    depends_on:
    - mongo
    links:
    - mongo
  mongo:
    restart: always
    image: mongo:latest
    environment:
    -  MONGO_INITDB_ROOT_USERNAME=4ip0llino
    -  MONGO_INITDB_ROOT_PASSWORD=KLVa4ip0
    volumes:
    - mongodb_data_container:/data/db
    ports:
    - "27017-27019:27017-27019"
volumes:
  mongodb_data_container: